defmodule VehiclesFleetMetrics.Repo.Migrations.CreateVehicles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:telemetry_readings) do
      modify :vehicle_id,
             references(:vehicles,
               column: :id,
               name: "telemetry_readings_vehicle_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:telemetry_readings, [:vehicle_id])
  end

  def down do
    drop_if_exists index(:telemetry_readings, [:vehicle_id])

    drop constraint(:telemetry_readings, "telemetry_readings_vehicle_id_fkey")

    alter table(:telemetry_readings) do
      modify :vehicle_id, :uuid
    end
  end
end
