defmodule VehiclesFleetMetrics.Repo.Migrations.CreateVehicles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:telemetry_readings) do
      add :speed, :float
      add :acceleration, :float
      add :temperature, :float
      add :status, :text
      add :event, :text
    end
  end

  def down do
    alter table(:telemetry_readings) do
      remove :event
      remove :status
      remove :temperature
      remove :acceleration
      remove :speed
    end
  end
end
