defmodule VehiclesFleetMetrics.Repo.Migrations.CreateVehicles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vehicles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :vin, :text, null: false
    end

    create table(:telemetry_readings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :vehicle_id, :uuid, null: false
      add :odometer, :float, null: false
      add :fuel_level, :float, null: false
      add :lat, :float, null: false
      add :lng, :float, null: false
      add :recorded_at, :utc_datetime, null: false
    end
  end

  def down do
    drop table(:telemetry_readings)

    drop table(:vehicles)
  end
end
